version: '2'
services:
    advances-app:
        image: advances
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://advances-postgresql:5432/advances
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    advances-postgresql:
        extends:
            file: postgresql.yml
            service: advances-postgresql
